events { worker_connections 1024; }

http {
    upstream backend_nodes {
        server backend1:3000;
        server backend2:3000;
        server backend3:3000;
    }

    server {
        listen 80;

        client_max_body_size 10M;

        # Servir archivos estáticos (logos) directamente desde el volumen compartido
        location /uploads {
            alias /app/uploads;
            expires 7d;
            add_header Cache-Control "public, immutable";
        }

        # Redirige las consultas de datos al clúster de Node.js
        location /api {
            proxy_pass http://backend_nodes;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Redirige React y permite WebSockets (Soporte para Vite HMR)
        location / {
            proxy_pass http://frontend:5173;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
