events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;

    upstream backend_servers {
        server 26.6.46.120:3000 max_fails=3 fail_timeout=10s;
        server 26.68.45.97:3000 max_fails=3 fail_timeout=10s;
        server 26.97.251.131:3000 max_fails=3 fail_timeout=10s;
    }

    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /uploads {
            alias /usr/share/nginx/uploads;
            expires 7d;
            add_header Cache-Control "public, immutable";
        }
    }
}
